export default {
  discoverMovie: {
    url: '/discover/movie?region=&sort_by=&certification_country=&certification=&certification.lte=&include_adult=&include_video=&page=&primary_release_year=&primary_release_date.gte=&primary_release_date.lte=&release_date.gte=&release_date.lte=&vote_count.gte=&vote_count.lte=&vote_average.gte=&vote_average.lte=&with_cast=&with_crew=&with_companies=&with_genres=&with_keywords=&with_people=&year=&without_genres=&with_runtime.gte=&with_runtime.lte=&with_release_type=&with_original_language=',
    optional: [
      'region',
      'sort_by',
      'certification_country',
      'certification',
      'certification.lte',
      'include_adult',
      'include_video',
      'page',
      'primary_release_year',
      'primary_release_date.gte',
      'primary_release_date.lte',
      'release_date.gte',
      'release_date.lte',
      'vote_count.gte',
      'vote_count.lte',
      'vote_average.gte',
      'vote_average.lte',
      'with_cast',
      'with_crew',
      'with_companies',
      'with_genres',
      'with_keywords',
      'with_people',
      'year',
      'without_genres',
      'with_runtime.gte',
      'with_runtime.lte',
      'with_release_type',
      'with_original_language',
    ],
  },
};
